openapi: 3.1.3
info:
  title: Dernier Métro API
  version: 1.0.0
servers:
  - url: http://localhost:3000
paths:
  /api:
    get:
      summary: Health check de l'API
      responses:
        '200':
          description: API en ligne
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: Hello Everyone
                  status:
                    type: string
                    example: success

  /db:
    get:
      summary: Health check de la base de données
      responses:
        '200':
          description: Base de données connectée
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    example: ok
                  message:
                    type: string
                    example: Database is connected
        '500':
          description: Erreur de connexion à la base
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    example: error
                  message:
                    type: string
                    example: Database connection failed
                  error:
                    type: string

  /last-metro:
    get:
      summary: Heure du dernier métro pour une station donnée
      description: >
        Retourne l'heure du dernier métro pour la station passée en query param.
        La recherche est insensible à la casse.
      parameters:
        - in: query
          name: station
          schema:
            type: string
          required: true
          description: Nom exact de la station (ex. "Châtelet")
      responses:
        '200':
          description: Informations sur le dernier métro
          content:
            application/json:
              schema:
                type: object
                properties:
                  station:
                    type: string
                  lastMetro:
                    type: string
                    example: "00:47"
                  line:
                    type: string
                    example: "M1"
                  tz:
                    type: string
                    example: "Europe/Paris"
        '400':
          description: Paramètre `station` manquant
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                  error:
                    type: string
        '404':
          description: Station non trouvée
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: Station not found
        '500':
          description: Erreur interne du serveur
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                  error:
                    type: string

  /next-metro:
    get:
      summary: Prochain passage de métro pour une station donnée
      description: >
        Retourne les prochains passages pour la station passée en query param.  
        Le paramètre `n` permet de limiter le nombre de prochains passages (max 5).  
        Si le service est fermé, retourne un message "Service closed".
      parameters:
        - in: query
          name: station
          schema:
            type: string
          required: true
          description: Nom exact de la station
        - in: query
          name: n
          schema:
            type: integer
            minimum: 1
            maximum: 5
          required: false
          description: Nombre de prochains passages (min 1 / max 5)
      responses:
        '200':
          description: Informations sur les prochains passages
          content:
            application/json:
              schema:
                type: object
                properties:
                  station:
                    type: string
                  ligne:
                    type: string
                  arrivals:
                    type: array
                    items:
                      type: string
                    description: Horaires des prochains passages (ex. ["12:34", "12:37"])
                  message:
                    type: string
                    description: Message facultatif (ex. "Service closed")
                  timeZone:
                    type: string
        '400':
          description: Paramètre `station` manquant
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                  error:
                    type: string
        '404':
          description: Station non trouvée
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                  suggestions:
                    type: array
                    items:
                      type: string
