openapi: 3.1.3
info:
  title: Dernier Métro API
  version: 1.0.0
servers:
  - url: http://localhost:3000
paths:
  /api:
    get:
      summary: Health check de l'API
      responses:
        '200':
          description: API en ligne
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: Hello Everyone
                  status:
                    type: string
                    example: success

  /db:
    get:
      summary: Health check de la base de données
      responses:
        '200':
          description: Base de données connectée
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    example: ok
                  message:
                    type: string
                    example: Database is connected
        '500':
          description: Erreur de connexion à la base
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    example: error
                  message:
                    type: string
                    example: Database connection failed
                  error:
                    type: string

  /:
    get:
      summary: Prochain passage de métro
      parameters:
        - in: query
          name: station
          schema:
            type: string
          required: true
          description: Nom exact de la station
        - in: query
          name: n
          schema:
            type: integer
            minimum: 1
            maximum: 5
          required: false
          description: Nombre de prochains passages (max 5)
      responses:
        '200':
          description: Informations sur le prochain métro
          content:
            application/json:
              schema:
                type: object
                properties:
                  station:
                    type: string
                  ligne:
                    type: string
                    description: Lignes desservant la station
                  arrivals:
                    type: array
                    items:
                      type: string
                    description: Horaires des prochains passages
                  timeZone:
                    type: string
        '400':
          description: Paramètre manquant
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                  error:
                    type: string
        '404':
          description: Station non trouvée
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                  suggestions:
                    type: array
                    items:
                      type: string
